### PR TITLE
Fix to prevent EMFILE error from occuring

### PR DESCRIPTION
**Pull request by slkuo230**

### CODE REVIEW

**Comment by aredridel** [comment]
Reasonable hack. Won't fix all cases, but it'll fix cases that involve that fs module instance.

**Comment by aredridel** [comment]
Can I get you to remove the version bump commit? That's something the releasing person does, not for every change to the release branch

**Comment by slkuo230** [comment]
@aredridel thanks for the quick response! I reverted "version bump" from the PR. :+1:

**Comment by grawk** [comment]
Looks good to me! :+1:

**Comment by aredridel** [comment]
version 0.2.4 is published

**Comment by slkuo230** [comment]
Awesome! Thank you!

**Pull request merged**
